# Generated by Django 5.0.4 on 2024-04-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_category_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.ImageField(
                default="No photo", upload_to="posts/%Y/%m/%d/", verbose_name="Фото"
            ),
        ),
    ]
