# Generated by Django 5.0.4 on 2024-04-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_post_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=200, verbose_name=""),
        ),
    ]
